### PR TITLE
Specs for MicroEvent

### PR DESCRIPTION
**Pull request by kiltec**
Spec'ed MicroEvent.
Mixin specs will come in another pull request in the next days.

Huh, why the heck are there those merge-commits appearing in this pull request?

### CODE REVIEW

**Comment by glaubinix** [comment]
the MicroEvent is actually an external library from https://github.com/jeromeetienne/microevent.js. I just saw now that the lib file is missing an origin. I do not think that we should have tests for that library. Though I am pretty sure that the owner of the original library will be more than happy about a pull request from you.

#16

**Comment by kiltec** [comment]
Noooooooooooooooooooooooooooooooooooooooooo! :S

**Comment by glaubinix** [comment]
I am really sorry about this. The file was added in a hurry because we needed some sort of event dispatcher and at the time it seemed logical for everyone to find external libraries in lib/

**Comment by kiltec** [comment]
Well, let's see if it gets accepted by the original author.
Worst case, I learned even more about Jasmine. :D

**Pull request closed without merging**
