### PR TITLE
Add bower.json to add development dependency on Jasmine 1.3.1

### PR DESCRIPTION
**Pull request by kiltec**
Not sure if you guys want to use Bower but in case you do, here's a bower.json to add Jasmine as a dependency.
I didn't know which version the conf schedule currently has, so I went ahead and picked 0.1.0.
Bower expects the versioning to adhere to SemVer.

Anyways, if you have bower installed, Jasmine will be installed with "bower install".

### CODE REVIEW

**Comment by glaubinix** [comment]
Thanks!
Though I think before we merge this, we should decide whether we want to use bower or npm because having both of them in one small projects is kind of over powered. If we want grunt then it might make more sense to use npm.

**Comment by kiltec** [comment]
Ah, right, npm.
Though, can you even install Jasmine using npm? When I look at https://npmjs.org/browse/keyword/jasmine, then I'm ... confused.

**Comment by kiltec** [comment]
Ah, not confused anymore, it's simply this one, I guess:
https://npmjs.org/package/jasmine-node
So npm is fine, I guess.

If I understood it correctly, the main advantage of bower is that it provides more packages which can only be run in the browser, while npm, obviously, only supports node.js packages.
But you need npm anyways to install bower, so npm is the better option, probably.

You can close this pull request, I guess. :D

**Comment by BattleRattle** [comment]
> You can close this pull request, I guess. :D

Your wish is my command :)

**Pull request closed without merging**
