### PR TITLE
Specs for PluginFactory

### PR DESCRIPTION
**Pull request by kiltec**
For this to work you have to manually download and unzip Jasmine (https://github.com/downloads/pivotal/jasmine/jasmine-standalone-1.3.0.zip) in a folder called "jasmine".
Necessary until it's decided which package manager to use that will then install Jasmine.

### CODE REVIEW

**Comment by kiltec** [comment]
Added a first real spec for PluginFactory.

I gotta say, Jasmine has been a bit underwhelming so far. Its documentation is pretty basic. I had to check the source code in order to learn how to use "toThrow()" for our use case.
If you should ever use toThrow() remember to always pass the actual expected Error into it, otherwise the spec will also pass for errors you didn't actually expect.

Anyways, we'll see how this turns out, maybe it's just me...

How do we proceed with this PR? Should it be left open until all specs for the PluginFactory are done?

**Comment by kiltec** [comment]
Actually, I'm going to finish this soon, so please leave this PR open.

**Comment by kiltec** [comment]
Ok, that should be it, ready for merging.

**Comment by glaubinix** [comment]
:+1:  awesome, thank you!

**Pull request merged**
